info:
  contact:
    email: classconnectingsoft2@gmail.com
    name: El mejor grupo de todos ndea deau
    url: https://github.com/classconnect-grupo3
  description: API for managing courses and related resources
  title: Courses Service API
  version: "1.0"
paths: {}
swagger: "2.0"
