# v2 schema must be exactly "2"
version: "2"

linters:
  # choose your default set: "standard", "all", "fast" or "none"
  default: all

  # disable linters you don’t want
  disable:
    - govet  # example

  # settings for individual linters MUST live under linters.settings
  settings:
    misspell:
      locale: US
    # ... your other linters-settings here ...

formatters:
  # if you previously enabled formatters under linters.enable,
  # move them here. e.g.:
  enable:
    - goimports
    - gci

issues:
  # to keep the built‑in excludes, or disable them:
  use-default-excludes: false

  # your exclude‑patterns (these replace top‑level "exclude")
  exclude-rules:
    - linters:
        - errcheck
      text: "error return value .* is not checked"

  # group-by → this moved under issues.group-by
  group-by: source

  # severity rules moved under issues.severity
  severity:
    rules:
      - path: ".*\\.go"
        text: "@linter"    # keep each linter’s default severity

  # if you want to exclude whole dirs:
  exclude-dirs:
    - vendor

output:
  # the new `formats:` block replaces deprecated format/sort-results
  formats:
    text:
      print-linter-name: true
      print-issued-lines: true
      colors: auto
  sort-order:
    - linter
    - severity
    - file
  show-stats: true
  path-prefix: ""        # if you need to strip/​add prefixes

run:
  timeout: 5m
  tests: false
  relative-path-mode: cfg
  issues-exit-code: 2
  # skip-dirs was removed — use issues.exclude-dirs instead
  build-tags: []

severity:
  default: error
