services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    env_file:
      - ./src/.env.dev
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  app:
    build: .
    container_name: courses-service
    restart: always
    env_file:
      - ./src/.env.dev
    ports:
      - "9090:9090"
    depends_on:
      - mongodb

volumes:
  mongodb_data:
