services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    env_file:
      - ./src/.env.test
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=test_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - courses-network
    command: mongod --quiet

  rabbitmq-test:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-test
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    logging:
      driver: "none"
    networks:
      - courses-network

  app-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: courses-service-test
    restart: "no"
    env_file:
      - ./src/.env.test
    environment:
      - DB_URI=mongodb://admin:password@mongodb:27017/test_db?authSource=admin
      - RABBITMQ_URL=amqp://admin:password@rabbitmq-test:5672/
      - NOTIFICATIONS_QUEUE_NAME=notifications_test
    depends_on:
      - mongodb
      - rabbitmq-test
    networks:
      - courses-network
    volumes:
      - ./coverage:/app/coverage

volumes:
  mongodb_data: {}
  rabbitmq_data: {}

networks:
  courses-network:
    driver: bridge
