services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    env_file:
      - ./src/.env.test
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=test_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - courses-network

  app:
    build: .
    container_name: courses-service
    restart: always
    env_file:
      - ./src/.env.test
    ports:
      - "9090:9090"
    depends_on:
      - mongodb
    networks:
      - courses-network

volumes:
  mongodb_data: {}

networks:
  courses-network:
    driver: bridge
